/*
 *  Copyright (c) 2014, Lukas Tenbrink.
 *  * http://lukas.axxim.net
 */

// Date: 8-4-2013 14:29:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.psychedelicraft.client.render;

import net.minecraft.client.model.*;
import net.minecraft.client.render.RenderLayer;
import net.minecraft.client.render.entity.model.*;
import net.minecraft.client.render.entity.state.PigEntityRenderState;

public class RastaHeadModel extends EntityModel<PigEntityRenderState> {
    public RastaHeadModel() {
        super(TexturedModelData.of(getModelData(Dilation.NONE), 128, 64).createModel(), RenderLayer::getEntityTranslucent);
    }

    public static ModelData getModelData(Dilation dilation) {
        ModelData data = new ModelData();
        ModelPartData root = data.getRoot();
        ModelPartData head = root.addChild(EntityModelPartNames.HEAD, ModelPartBuilder.create()
                .uv(0, 0).cuboid(-4, -8, -4, 8, 8, 8, dilation).mirrored(), ModelTransform.NONE);
        head.addChild("nose", ModelPartBuilder.create()
                .uv(33, 0).cuboid(-0.5F, -4.8F, -5F, 1, 2, 1, dilation).mirrored(), ModelTransform.rotation(-0.0743572F, 0, 0));
        head.addChild("nostrils", ModelPartBuilder.create()
                .uv(38, 0).cuboid(-1F, -4.2F, -4.5F, 2, 1, 1, dilation).mirrored(), ModelTransform.NONE);
        head.addChild("hair", ModelPartBuilder.create()
                .uv(0, 17).cuboid(-4.5F, -7.5F, -4.5F, 9, 11, 9, dilation).mirrored(), ModelTransform.NONE);
        root.addChild(EntityModelPartNames.HAT, ModelPartBuilder.create()
                .uv(0, 38).cuboid(-5F, -10F, -8.5F, 10, 7, 12, dilation).mirrored(), ModelTransform.rotation(-0.669215F, 0, 0));
        root.addChild("joint", ModelPartBuilder.create()
                .uv(0, 0).cuboid(-0.5F, -3.5F, -5F, 1, 1, 2, dilation).mirrored(), ModelTransform.rotation(0.4089647F, -0.2602503F, 0));
        return data;
    }
}
