org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=1.21.5
  yarn_mappings=1.21.5+build.1
  loader_version=0.16.10
  fabric_version=0.119.6+1.21.5

# Mod Properties
  group=ivorius
  displayname=Psychedelicraft
  authors=Ivorius, TripleHeadedSheep
  description=Adds drugs into Minecraft. Psychedelicraft specializes on realism and effects. Shaders are being utilized, so keep that in mind.

# Publishing
  modrinth_loader_type=fabric
  modrinth_project_id=8u2zZjRq

# Dependencies
  minecraft_version_range=>=1.21.5
  fabwork_version=1.3.2+1.21
  kirin_version=1.20.5+1.21.5
  modmenu_version=14.0.0-rc.2

  use_iris=0
  use_sodium=1
  iris_version=1.8.11+1.21.5-fabric
  sodium_version=mc1.21.5-0.6.12-fabric

# TMI Testing
  tla_version=1.2.2-beta.4+1.21
  tmi_type=none
  emi_version=1.1.12+1.21
  rei_version=18.0.804
	  rei_architectury_version=15.0.2
		rei_cloth_basic_math_version=0.6.1
		rei_cloth_config_version=17.0.144
